# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-54-177-15-182.us-west-1.compute.amazonaws.com:3306/586oosdemo
    username: test
    password: 12345
mybatis-plus:
    mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8081
yiblog:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization
  upload:
    path: /files/
    realPath: /home/ubuntu/yiblog/files/
